%\VignetteIndexEntry{Oligo Vignette}
%\VignetteDepends{oligo}
%\VignetteKeywords{Expression, SNP, Affymetrix, NimbleGen, Oligonucleotide Arrays}
%\VignettePackage{oligo}
\documentclass{article}

\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}
\newcommand{\Rcode}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textsf{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}
\newcommand{\oligo}{\Rpackage{oligo }}

\usepackage{graphicx}

\begin{document}
\title{An Introduction to the Oligo Package}
\date{March, 2007}
\author{Benilton Carvalho}
\maketitle

<<setup, echo=FALSE, results=hide>>=
options(width=60)
options(continue=" ")
options(prompt="R> ")
@ 

\section{Introduction}

The \oligo package is designed to support all microarray designs
provided by Affymetrix and NimbleGen: expression, tiling, SNP and exon
arrays. With the increase in the density of the current technologies,
\oligo uses the resources offered by the \Rpackage{BufferedMatrix}
packages to handle the feature-level information. As of now,
chip-specific packages are built via \Rpackage{makePlatformDesign} and
transitioning to the \Rpackage{pdInfoBuilder} package, which creates
the data packages for the Affymetrix SNP arrays.

\section{Analyzing Affymetrix SNP Arrays}

Genotyping can be performed using \oligo and you will need:

\begin{itemize}
\item \oligo and its dependencies;
\item Chip specific data package, eg. \Rpackage{pd.mapping50k.xba240}:
  package that contains the array specifications and SNP annotation.
\item CEL files.
\end{itemize}

Figure \ref{workflow} shows the general workflow for genotyping using
the \oligo package. 

\begin{figure}[h]
  \centering
  \includegraphics[scale=.5]{workflow.png}
  \caption{Genotyping workflow using the \oligo package.}
  \label{workflow}
\end{figure}

We will start by loading the \oligo package and importing the CEL
files available on the \Rpackage{sampleDataAffy100K}. The intensity
matrix will be a \Rclass{BufferedMatrix} object and this will require
the use of temporary files in order to reduce the RAM usage. Although
the temporary files can be stored anywhere, a better approach will be
to use a local directory rather than using a directory on the
network. The \Robject{tmpdir} in the \Rfunction{read.celfiles()} sets
the directory where the temporary files are going to be stored.

<<getRawData>>=
library(oligo)
library(hapmap100kxba)
pathCelFiles <- system.file("celFiles", package="hapmap100kxba")
fullFilenames <- list.celfiles(path=pathCelFiles, full.names=TRUE)
temporaryDir <- tempdir()
rawData <- read.celfiles(fullFilenames, tmpdir=temporaryDir)
@ 

The \Robject{rawData} object is of class \Rclass{SnpFeatureSet}, which
extends \Rclass{eSet}. Methods like \Rmethod{exprs()} and
\Rmethod{pm()} are defined and, again, return \Rclass{BufferedMatrix}
objects.

The \Rclass{phenoData} slot includes covariates about the
samples. Genotyping and copy number analyses often make use of gender
information in order to provide more precise inferences. The code
below exemplifies the creation of the \Rclass{phenoData} object.

<<setPD>>=
aboutSamples <- data.frame(gender=c("female", "female", "male"))
rownames(aboutSamples) <- sampleNames(rawData)
aboutVars <- data.frame(labelDescription="male/female")
rownames(aboutVars) <- "gender"
phenoData(rawData) <- new("AnnotatedDataFrame",
                          data=aboutSamples,
                          varMetadata=aboutVars)
@ 

Preprocessing SNP arrays can be done by using the \Rfunction{snprma()}
method, described in \cite{Carvalho2006}. Once it is completed, an
\Rclass{SnpQSet} object is returned, which is the summarized data of the
\Robject{rawData} object above. An overview of the method is presented
at Figure \ref{snprma}.

\begin{figure}[h]
  \centering
  \includegraphics[scale=.5]{snprma.png}
  \caption{SNPRMA overview}
  \label{snprma}
\end{figure}

For each SNP there are four numbers $(\theta_{A-}, \theta_{B-},
\theta_{A+}, \theta_{B+})$, which are proportional to the
log-intensities in each of these combinations of allele and strand
($-$: antisense; $+$: sense). They are represented by four matrices:
\Robject{antisenseThetaA}, \Robject{antisenseThetaB},
\Robject{senseThetaA} and \Robject{senseThetaB}, which are the
components of the \Rclass{SnpQSet} object. One can extract these
objects using accessors of the same name.

Average intensities and log-ratios are defined as across allele and
within strand, ie:
\begin{eqnarray}
  A_{s} & = & \frac{\theta_{A, s}+\theta_{B, s}}{2} \\
  M_{s} & = & \theta_{A, s} - \theta_{B, s},
\end{eqnarray}
where $s$ defines the strand (antisense or sense). These quantities
can be obtained via \Rmethod{getA()} and \Rmethod{getM} methods, which
return high-dimensional arrays with dimensions corresponding to SNP's,
samples and strands, respectively.
<<snprma, cache=TRUE>>=
preProcessedData <- snprma(rawData)
theA <- getA(preProcessedData)
theM <- getM(preProcessedData)
dim(theA)
str(theM)
@ 

These measures can be used, for example, to create an MA-plot and are
later used for genotyping. The example below generates an MA-plot for
the first sample using only the antisense strand data:
<<maplot, fig=TRUE>>=
library(geneplotter)
smoothScatter(theA[,1,1], theM[,1,1], main="MA-plot (Antisense)",
              xlab="Average Intensity", ylab="Log-ratio (A/B)")
@ 

The CRLMM algorithm \cite{Carvalho2006} can be applied on a
\Rclass{SnpQSet} object in order to produce genotype calls. It involves
running a mixture of regressions via EM algorithm to adjust for average
intensity and fragment length in the log-ratio scale. These adjustments
may take long time to run, depending on the combination of number of
samples and computer resources available. To save time in subsequent
analyses, we must specify the name of the file that will store the
results obtained with the EM algorithm using the
\Robject{correctionFile} argument. If the file passed to
\Robject{correctionFile} does not exist, it is created, otherwise it is
loaded. Figure \ref{crlmm} presents a diagram of the CRLMM algorithm:

\begin{figure}[h]
  \centering
  \includegraphics[scale=.5]{crlmm.png}
  \caption{CRLMM Algorithm diagram}
  \label{crlmm}
\end{figure}

\textbf{A word of warning}: the \Rmethod{crlmm()} method searches for a
variable \Robject{gender} in the \Rclass{phenoData} slot of the
\Rclass{SnpQSet} object. If it fails to find that variable, it will try
estimate the gender from the data. If there is not enough discrimination
power to estimate the gender, the following error message will be
returned:

{\bf empty cluster: try a better set of initial centers}

Increasing the sample size is one of the possible solutions, although
the preferred one is to have \Robject{gender} already defined in the
\Rclass{phenoData} slot.

<<crlmm, cache=TRUE>>=
crlmmOut <- crlmm(preProcessedData,
                  correctionFile="exampleCorrection.rda",
                  verbose=FALSE)
@ 

The \Robject{crlmmOut} object above belongs to the \Rclass{SnpCallSet}
class and contains the genotype calls and confidence measures
associated to the calls, represented respectively by the
\Robject{calls} and \Robject{callsConfidence} matrices. These matrices
can be accessed using the methods of the same name as demonstrated
below:

<<theCalls>>=
calls(crlmmOut)[1:5,1:2]
callsConfidence(crlmmOut)[1:5,1:2]
@ 

The genotype calls are represented by 1 (AA), 2 (AB) and 3 (BB). The
confidence is the log-likelihood ratio of the two most likely calls.

\subsection{Exploring the Annotation Package}

The user who is willing to make deeper investigation using the
annotations provided for each SNP array can use SQL queries to access
more other information that might not be directly exposed.

The example below demonstrates how to see the available tables, fields
and extract chromosome, physical location and cytoband for the first
five SNP's (probes querying specific SNP's have names starting with
the string ``SNP'').

<<>>=
annot <- annotation(rawData)
conn <- db(get(annot))
dbListTables(conn)
dbListFields(conn, "featureSet")
sql <- "SELECT man_fsetid, chrom, physical_pos FROM featureSet WHERE man_fsetid LIKE 'SNP%' LIMIT 5"
dbGetQuery(conn, sql)
@ 
 
\section{Details}

This document was written using:

<<>>=
sessionInfo()
@ 


\end{document}
