## setGeneric("platform", function(object) standardGeneric("platform"))
## setGeneric("platform<-", function(object, value) standardGeneric("platform<-"))
## setGeneric("manufacturer",function(object) standardGeneric("manufacturer"))
## setGeneric("manufacturer<-",
##            function(object, value) standardGeneric("manufacturer<-"))

setGeneric("kind", function(object) standardGeneric("kind"))
setGeneric("getPlatformDesign",
           function(object) standardGeneric("getPlatformDesign"))
setGeneric("pm", function(object, subset=NULL, ...) standardGeneric("pm"))
setGeneric("pm<-", function(object, value) standardGeneric("pm<-"))
setGeneric("mm", function(object, subset=NULL) standardGeneric("mm"))
setGeneric("mm<-", function(object, value) standardGeneric("mm<-"))
setGeneric("featureIndex",
           function(object, which=c("both","pm","mm"), subset=NULL) {
               standardGeneric("featureIndex")
           })
setGeneric("logRatioAntisense", function(object) standardGeneric("logRatioAntisense"))
setGeneric("logRatioSense", function(object) standardGeneric("logRatioSense"))

## setGeneric("senseThetaA", function(object) standardGeneric("senseThetaA"))
## setGeneric("senseThetaB", function(object) standardGeneric("senseThetaB"))
## setGeneric("antisenseThetaA", function(object) standardGeneric("antisenseThetaA"))
## setGeneric("antisenseThetaB", function(object) standardGeneric("antisenseThetaB"))
## setGeneric("thetaA", function(object) standardGeneric("thetaA"))
## setGeneric("thetaB", function(object) standardGeneric("thetaB"))
## setGeneric("getM", function(object) standardGeneric("getM"))
## setGeneric("getA", function(object) standardGeneric("getA"))
setGeneric("genomeBuild", function(object) standardGeneric("genomeBuild"))
setGeneric("pmPosition", function(object) standardGeneric("pmPosition"))
setGeneric("pmOffset", function(object) standardGeneric("pmOffset"))
setGeneric("pmChr", function(object) standardGeneric("pmChr"))
setGeneric("probeNames", function(object, subset=NULL) standardGeneric("probeNames"))
setGeneric("nProbes", function(object) standardGeneric("nProbes"))
setGeneric("pmindex", function(object, ...) standardGeneric("pmindex"))
setGeneric("mmindex", function(object, ...) standardGeneric("mmindex"))
setGeneric("featureInfo", function(object) standardGeneric("featureInfo"))
setGeneric("listFeatureFields", function(object) standardGeneric("listFeatureFields"))
setGeneric("listFeatureSetFields", function(object) standardGeneric("listFeatureSetFields"))
setGeneric("pmFragmentLength", function(object) standardGeneric("pmFragmentLength"))
setGeneric("pmSequence", function(object, ...) standardGeneric("pmSequence"))
setGeneric("mmSequence", function(object) standardGeneric("mmSequence"))
setGeneric("pmAllele", function(object) standardGeneric("pmAllele"))
setGeneric("pmStrand", function(object) standardGeneric("pmStrand"))
setGeneric("hist", function(x, ...) standardGeneric("hist"))
setGeneric("boxplot", function(x, ...) standardGeneric("boxplot"))
setGeneric("image", function(x, ...) standardGeneric("image"))
setGeneric("nrow", function(x) standardGeneric("nrow"))
setGeneric("ncol", function(x) standardGeneric("ncol"))
setGeneric("rma", function(object, ...) standardGeneric("rma"))
setGeneric("geometry", function(object) standardGeneric("geometry"))
setGeneric("MAplot", function(object, ...) standardGeneric("MAplot"))
setGeneric("genotype", function(object, ...) standardGeneric("genotype"))

setGeneric("plotM", function(object, i, ...) standardGeneric("plotM"))
