setGeneric("getX", function(object, type) standardGeneric("getX"))
setGeneric("getY", function(object, type) standardGeneric("getY"))
setGeneric("bg", function(object, subset=NULL) standardGeneric("bg"))

setGeneric("pm", function(object, subset=NULL, ...) standardGeneric("pm"))
setGeneric("pm<-", function(object, value) standardGeneric("pm<-"))
setGeneric("mm", function(object, subset=NULL) standardGeneric("mm"))
setGeneric("mm<-", function(object, value) standardGeneric("mm<-"))
setGeneric("bg", function(object, subset=NULL) standardGeneric("bg"))
setGeneric("bg<-", function(object, value) standardGeneric("bg<-"))
setGeneric("logRatioAntisense", function(object) standardGeneric("logRatioAntisense"))
setGeneric("logRatioSense", function(object) standardGeneric("logRatioSense"))

setGeneric("hist", function(x, ...) standardGeneric("hist"))
##setGeneric("boxplot", function(x, ...) standardGeneric("boxplot"))
setGeneric("image", function(x, ...) standardGeneric("image"))
setGeneric("rma", function(object, ...) standardGeneric("rma"))
setGeneric("MAplot", function(object, ...) standardGeneric("MAplot"))
setGeneric("genotype", function(object, ...) standardGeneric("genotype"))

setGeneric("getContainer", function(object, probeType=c("pm", "bg")) standardGeneric("getContainer"))
